### ISSUE TITLE
repo access

### ISSUE THREAD

**Issue by jnoortheen** [xonsh/peg-parser#4]
@gforsyth I want to configure some CI services for this repo. I currently don't have settings access to this repo. Could you enable it ?

- [ ] Discussions
- [ ] cod-coverage
- [ ] cod-speed - or pytest-benchmark results with github pages

**Comment by gforsyth** [comment]
Hey @jnoortheen -- you should have admin privileges now on this repo (that should've been the default...)

**Comment by jnoortheen** [comment]
Thanks, now I have it
